### ISSUE TITLE
stixel input

### ISSUE THREAD

**Issue by Isaac80** [dhernandez0/stixels#1]
hi, 

I implemented the code with the available examples and it works. When i tried to implement on some dataset where left-image (pgm ) and disparity (pgm ) and I got duplicated stixels (it draws stixels correctly for first half of the image and reply on the second half) . Do I need to use the proposed gpu-sgm? thx

**Comment by dhernandez0** [comment]
Hi Isaac,

Can you please provide the files that do not work?

**Comment by Isaac80** [comment]
Hi Daniel, 

Thanks
[Uploading Archive 2.zip…]()

**Comment by Isaac80** [comment]
Hi Daniel, 

Please find attached. 
[Uploading Archive 2.zip…]()

**Comment by Isaac80** [comment]
Hi Daniel, 

could you please check your email, pgm files can't be uploaded here, thx

**Comment by Isaac80** [comment]
I think the problem for real scenes since the one included with the code works fine. I check the save_stixel function 
plz see below
[http://tinypic.com/r/2gturro/9](http://tinypic.com/r/2gturro/9)

**Comment by dhernandez0** [comment]
The problem was that the program was expecting images of 16 bits per pixel and also a bug which made images with height not multiple of 32 fail.
