### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by steve3nto** [dhernandez0/stixels#2]
I have tested the stixels code on a machine with NVIDIA Titan X, Cuda 8 and OpenCV 2.4

The code compiles, but when testing it at runtime using valgrind I get memory leaks, so the code can lead to a segmentation fault crash.
 So pretty much the code works properly sometimes, other times it crashes. Valgrind gave the following reasons for a crash:

==17706== Conditional jump or move depends on uninitialised value(s)
==17706==    at 0x406928: Stixels::Finish() (Stixels.cu:161)
==17706==    by 0x40440E: main (main.cu:227)
==17706== 
==17706== Conditional jump or move depends on uninitialised value(s)
==17706==    at 0x406939: Stixels::Finish() (Stixels.cu:162)
==17706==    by 0x40440E: main (main.cu:227)
==17706== 
It took an average of 46.4508 miliseconds, 21.5281 fps
==17706== 
==17706== HEAP SUMMARY:
==17706==     in use at exit: 5,417,827 bytes in 9,480 blocks
==17706==   total heap usage: 14,227 allocs, 4,747 frees, 18,739,217 bytes allocated
==17706== 
==17706== LEAK SUMMARY:
==17706==    definitely lost: 32,816 bytes in 1 blocks
==17706==    indirectly lost: 0 bytes in 0 blocks
==17706==      possibly lost: 928,302 bytes in 958 blocks
==17706==    still reachable: 4,456,709 bytes in 8,521 blocks
==17706==         suppressed: 0 bytes in 0 blocks
==17706== Rerun with --leak-check=full to see details of leaked memory
==17706== 
==17706== For counts of detected and suppressed errors, rerun with: -v
==17706== Use --track-origins=yes to see where uninitialised values come from
==17706== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

This error is a memory leak due to

delete[] m_prior_objfromground;
delete[] m_prior_objfromobj;

at line 161 and 162 of stixels.cu

It seems those pointers are initialized but never used and calling delete on them can cause a memory leak. I have commented out those two lines and the problem seems fixed.
Now the compiled code seems to run reliably, without crashing because of segmentation fault.

**Comment by dhernandez0** [comment]
Yes, you are right, thanks for the input.

**Comment by dhernandez0** [comment]
With the new version this should be solved.
