### ISSUE TITLE
Real time implementation of Stixel from Camera Images

### ISSUE THREAD

**Issue by shanuv** [dhernandez0/stixels#3]
Hi!
I have been trying to modify the code to use it on images fed real time via a ZED camera by combining the camera API and modifying the main.cu file to read from it rather than the folders specified. However, when I run it, the code is still using the images from the folder and unable to read from the camera. Could you please point out the places where I should modify the code to achieve this? I can then go through them one by one to do the same.

**Comment by dhernandez0** [comment]
solved by email :)

**Comment by yyuuliang** [comment]
so.... where to change?

**Comment by dhernandez0** [comment]
Hi!

You can do your own code that passes all the parameters to Stixels class (as you can see in main.cu), and use it as you can see in that file (stixels.Set*, .Initialize, .Compute, .GetStixels, .Finalize), it should be straightforward.
