### ISSUE TITLE
Error: invalid device function 8

### ISSUE THREAD

**Issue by yyuuliang** [dhernandez0/stixels#4]
hi
thanks for sharing this code. I tried to run the example but got an error said "Error: invalid device function 8". I didn't know where this came from as I searched all the source code and couldn't find this line.

I am using a laptop with Nvidia 1070 gpu, system is Ubuntu 16.04.

The full output is 
$ ./stixels ../example/ 128
ap_000_29-02-2016_09-00-09_000002.png
Camera Parameters -> Tilt: -0.484829 Height: 4.4689 vHor: 13 alpha_ground: 0.158384
Error: invalid device function 8
Error: invalid device function 8
Error: invalid device function 8
It took an average of 1.0762e-42 miliseconds, inf fps

thanks.

**Comment by dhernandez0** [comment]
Hi!

Probably that's because it's not running any kernel. Check the file CMakeLists.txt, remove all the lines:
-gencode=arch=compute_30,code=sm_30
...

And leave only your GPU architecture, I think it should be -gencode=arch=compute_61,code=sm_61

Please, let me know if that works for you.

**Comment by yyuuliang** [comment]
Hi
Thanks for the quick reply!
I will try it tonight and let you know the result.

**Comment by yyuuliang** [comment]
It works!
thanks
