### ISSUE TITLE
When I use CV_8U depth map, this project can not give an result.Could you help me?

### ISSUE THREAD

**Issue by wuxler** [dhernandez0/stixels#5]
~/DeepLearning/stixels-master/build$ ./stixels ../example 128
img.png
0
Camera Parameters -> Tilt: 0.681282 Height: -11.8573 vHor: 956 alpha_ground: -0.0524078
Error: invalid device function 8
Error: invalid device function 8
Error: invalid device function 8
It took an average of 1.00893e-42 miliseconds, inf fps
![stixels](https://user-images.githubusercontent.com/8352574/31770675-92f78eb0-b50b-11e7-8759-400a14f6143b.png)

**Comment by dhernandez0** [comment]
It looks as if you compiled the code for the incorrect GPU architecture, change "-gencode=arch=compute_xx,code=sm_xx" in CMakeLists.txt. xx= your GPU architecture
