### ISSUE TITLE
Can't compute road estimation

### ISSUE THREAD

**Issue by afekih** [dhernandez0/stixels#6]
Hello,
I compiled your project as you shown, and when I tried to execute the example with "./stixels ../example 128" I got : 
ap_000_29-02-2016_09-00-09_000002.png
Can't compute road estimation
It took an average of -nan miliseconds, -nan fps
If you do know where is the problem, thank you in advance for your answer.

**Comment by dhernandez0** [comment]
it looks like a compilation issue:

Very fast execution and incorrect result: This is usually an error related to the compute architecture used. Look at the CMakeLists.txt and change the architecture to the one you are using, please. If you run the application with nvprof you will see that it does not run any CUDA kernel
